volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: taski_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: guineapigproger/taski_backend
    container_name: taski_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
    restart: always

  frontend:
    image: guineapigproger/taski_frontend
    container_name: taski_frontend
    volumes:
      - static:/app/build
    restart: always

  gateway:
    image: guineapigproger/taski_gateway
    container_name: taski_gateway
    ports:
      - "8000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    restart: always
